// This file is auto-generated by EnumFIleGenerator.
// If you change this file without a correct procedure,
// the integrity between source and this file may be destroyed.


namespace Azarashi.CerkeOnline.Application.Language
{
	enum TranslatableKeys
	{
		HandsTheUnbeatable,
		HandsTheSocialOrder,
		HandsTheCulture,
		HandsTheCavalry,
		HandsTheAttack,
		HandsTheKing,
		HandsTheAnimals,
		HandsTheArmy,
		HandsTheComrades,
		HandsTheDeadlyArmy,
		HandsTheStepping,
		HandsTheFutileMove,
		HandsTheFlash,
		Hand,
		Capture,
		PiecesVessel,
		PiecesPawn,
		PiecesArcher,
		PiecesChariot,
		PiecesTiger,
		PiecesHorse,
		PiecesOfficer,
		PiecesShaman,
		PiecesGeneral,
		PiecesKing,
		PiecesMind
	}
}
