// This file is auto-generated by EnumFIleGenerator.
// If you change this file without a correct procedure,
// the integrity between source and this file may be destroyed.


namespace Azarashi.CerkeOnline.Application.Language
{
	public enum TranslatableKeys
	{
		HandsTheUnbeatable = 0,
		HandsTheSocialOrder = 1,
		HandsTheCulture = 2,
		HandsTheCavalry = 3,
		HandsTheAttack = 4,
		HandsTheKing = 5,
		HandsTheAnimals = 6,
		HandsTheArmy = 7,
		HandsTheComrades = 8,
		HandsTheDeadlyArmy = 9,
		HandsTheStepping = 10,
		HandsTheFutileMove = 11,
		HandsTheFlash = 12,
		Hand = 13,
		Capture = 14,
		PiecesVessel = 15,
		PiecesPawn = 16,
		PiecesArcher = 17,
		PiecesChariot = 18,
		PiecesTiger = 19,
		PiecesHorse = 20,
		PiecesOfficer = 21,
		PiecesShaman = 22,
		PiecesGeneral = 23,
		PiecesKing = 24,
		PiecesMinds = 25,
		CurrentPlayerLabel = 26,
		MyScoreLabel = 27,
		EnemyScoreLabel = 28,
		CurrentSeasonLabel = 29,
		CastSticksButton = 30,
		HandCompleteMessage = 31,
		HandUncompleteMessage = 32
	}
}
